language: php

env:
  - QUNIT=false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  include:
    - php: 5.3
      env: QUNIT=true

before_script:
  - composer install --prefer-source

script: bash ./build/travis/script.sh

notifications:
  email:
    recipients:
      - jeroendedauw@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"
